name: API Deploy

on:
  push:
    branches: [master]
    paths:
      - "**.js"
      - "**.json"

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    needs: [testing]
    runs-on: [self-hosted, api, nodejs]
    strategy:
      max-parallel: 1
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - name: Merge changes
      run: |
        sudo git pull
