name: API Deploy

on:
  push:
    branches: [master]
    paths:
      - "**.js"
      - "**.json"
      - "**.pug"
      - "**.txt" 
      - "**.yml"

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    needs: [testing]
    runs-on: [self-hosted, api, nodejs, knotters]
    strategy:
      max-parallel: 1
      matrix:
        node-version: [16.x]

    steps:
    - name: Merge changes
      run: |
        git pull origin master
    - run: npm install 
    - run: echo "${{ secrets.ENV_PROD }}" > .env 
    - run: pm2 reload ecosystem.config.js --update-env

